keys:
  # User age key (from ~/.config/sops/age/keys.txt)
  - &user_age age1r659axr93ksycmxywkskv49sm88q5xvledr8kwghvr7eeahrrefsl2aptw
  # SSH-derived age key (from ~/.ssh/id_ed25519.pub)
  - &ssh_age age1p7zpmfhdnrdul90k3ntwa7hmp70u2v2p800uu6fxcdcg39vpl9qsdgkyhu

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_age
          - *ssh_age
