name: dev
root: .
windows:
  - code:
      layout: even-horizontal
      panes:
        - omx resume
  - ops:
      layout: main-vertical
      panes:
        - bv
        - foreman status --watch
        - ""
