#!/usr/bin/env bash
set -x

declare -a color

SPACEBAR_HEIGHT=$(spacebar -m config height)

color["focused"]="0xE01EF701"
color["normal"]="0xE0F7F217"
color["preselect"]="0xE0F72B18"

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config layout bsp
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config normal_window_border_color "0xEO1EF701"
yabai -m config active_window_border_color "0xE0F7F217"
yabai -m config insert_feedback_color "${color["preselect"]}"
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding "$SPACEBAR_HEIGHT"
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 06

# setup spaces

# float system preferences
yabai -m rule --add app="(Preferences|Install|Parallels|Steam)" manage=off
yabai -m rule --add app="Zoom" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Setapp" app="^Setapp$" manage=off
yabai -m rule --add label="Karabiner" app="^Karabiner-Elements$" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" manage=off
yabai -m rule --add label="Hammerspoon" app="^Hamerspoon$" manage=off
yabai -m rule --add label="Hammerspoon Console" app="^Hamerspoon Console$" manage=off
yabai -m rule --add label="Zoom" app="^zoom.us$" manage=off
yabai -m rule --add label="1Password" app="^1Password$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# spacebar
yabai -m config external_bar all:"$SPACEBAR_HEIGHT":0
yabai -m rule --add --label=emacs app=Emacs manage=on
set +x

echo "yabai configuration loaded.."
